config/routes.rb
VideoApp::Application.routes.draw do
  root to: 'videos#index'
  get "users/new", to: 'users#new', as: :signup
  post "/sessions", to: 'sessions#create', as: :sessions
  post '/users', to: 'users#create'
  delete '/sessions', to: 'sessions#destroy', as: :signout

  resources :videos, only: [:index, :create, :destroy, :show, :update]

  delete '/videos/:id/:delete_key', to: "videos#destroy", as: :delete_video_with_key

  get '/users/:id', to: 'users#show', as: :show_user

  get '/videos/:id/d/:delete_key', to: 'videos#delete_page', as: :delete_video_page

  get '/new', to: 'videos#new_new'

get '/hw/uploaded/:id', to: 'site#index'
  get '/hw/encoded/:id', to: 'site#index'

  post '/hw/uploaded/:id', to: 'my_heywatch#upload_complete'
  post '/hw/encoded/:id', to: 'my_heywatch#encode_complete'

end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  url         :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  attachment  :string(255)
#  extension   :string(255)
#  session_id  :string(255)
#  user_id     :integer
#  delete_key  :string(255)
#

class Video < ActiveRecord::Base
	belongs_to :user
	#mount_uploader :attachment, VideoUploader

      before_validation(on: :create) do
        self.views = 0
        self.processed = "processed"
      end

	def create_url filepath
		self.url = "http://d1f5gutkqysysk.cloudfront.net#{filepath}"
		self.get_extension
	end

	def get_extension
		self.extension = self.url.split(".").last
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  #list all videos title and page link
  def index
    @videos = current_user.videos if signed_in?
    @videos ||= []
    @video = Video.new
  end

  #create a video
  #use a session and a delete key to allow the user to edit the video if they are not signed in
  #attach the video to their user account if they are signed in
  def create 
    @video = Video.new()                                                                     #get the attachemnt and create a video object with it

    if @video.save                                                                                   #if it saves then get the urll
      @video.create_url(params[:filepath])                                         

      if signed_in?                                                                                    #if the user is signed in add the video to their account
        current_user.videos << @video 

      else                                                                                                   #if they arent't uses sessions and a delete key
        @video.session_id = SecureRandom.urlsafe_base64(15) 
        @video.delete_key = SecureRandom.urlsafe_base64(30) 
        session[:owned_videos] ||= []                                                    #if the current session doesn't have any owned_videos then create the array
        session[:owned_videos] << @video.session_id                      #add videos session id to array
      end

      @video.save 
      send_to_heywatch @video
      render json:  {url: "/videos/#{@video.id}"}
    else                                                                                     #error saving the video take them back to try again TODO show errors
      redirect_to "/"
      
    end
  end
  #display the video
  #set the owner_type to one of 3 options
  #owner             -  the user is signed in and owns the video
  #not signed in - the user is not signed in but owns the video through the session
  #not owner      - the user doesn't own the video
  def show
    @video = Video.find(params[:id])
    @video.views ||= 0
    @video.views += 1

    @video.save
    if owner? @video.user_id                                                        #for logged in owners of the video
      @owner_type = "owner" 
    elsif not_signed_in_owner? @video                                        #for non logged in owners of the video
      @owner_type = "not signed in"
    else                                                                                         #normal view of the video
      @owner_type = "not owner"
    end

  end

  #the page a non logged in user can use to delete the video
  #will only show up with a valid delete key
  def delete_page

    @video = Video.find(params[:id])
    if params[:delete_key] && params[:delete_key] == @video.delete_key #only show the page if the key matches
      render 'delete_page' 
    else                                                                                                                    #redirect to home if invalid
      redirect_to "/"
                                                                                                                              #TODO not authorized error
    end

  end

  # update the video only if the current user owns it through their account or session
  def update
    @video = Video.find(params[:id])
    if owner?(@video.user_id)|| not_signed_in_owner?(@video)
      @video.update(video_title)
      redirect_to video_path(@video.id)
    else
                                                                                                                            #TODO not authorized error
      redirect_to "/"
    end
  end

  # destroy only if owner or delete key is valid
  def destroy
    @video = Video.find(params[:id])
    #first check if the user is logged in and the owner otherwise see if the delete key is valid
    if ((@video.user_id && owner?(@video.user_id)) || (params[:delete_key] && @video.delete_key && @video.delete_key == params[:delete_key]))
      @video.destroy
      redirect_to videos_path, notice:  "The video #{@video.name} has been deleted."
    else
      redirect_to videos_path, notes: "You are not authorized to delete this video"
    end

  end

  private

  def send_to_heywatch video
    hw = HeyWatch.new
    title = ((video.name || "untitled") + video.id.to_s + SecureRandom.urlsafe_base64(3))
    video.attachment = title
    video.save
    hw.create :download, {
      :url => video.url, 
      title: title,
      :ping_url => "http://web1.tunnlr.com:13011/hw/uploaded/#{video.id}" #local
      #:ping_url => "http://easyvid.heroku.com/hw/uploaded/#{video.id}" #web
    }
  end
  def video_title
    params.require(:video).permit(:name)
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_new_upload.html.erb
<div class="container">
  <h2>Upload file</h2>
  <%= form_for @video, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
      <div class="span7">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
          <i class="icon-plus icon-white"></i>
          <span>Add files...</span>
          <%= f.file_field :attachment %>
        </span>
        </div>
      </div>
    <!-- The loading indicator is shown during image processing -->
    <div class="fileupload-loading"></div>
    <br>
    <!-- The table listing the files available for upload/download -->
    <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
    </table>
  <% end %>

</div>
<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">

  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-striped"><div class="bar progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>{%=locale.fileupload.start%}</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
        <td class="preview">{% if (file.thumbnail_url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
          {% } %}</td>
        <td class="name">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
        {% } %}
      
    </tr>
    {% } %}
</script>

<script type="text/javascript" charset="utf-8">
  $(function () {
    
      // Initialize the jQuery File Upload widget:
      $('#fileupload').fileupload();
      // 
      // Load existing files:

      $.getJSON($('#fileupload').prop('action'), function (files) {
        var fu = $('#fileupload').data('blueimpFileupload'), 
          template;
        fu._adjustMaxNumberOfFiles(-files.length);
        console.log("poopy");
        console.log(files);
        template = fu._renderDownload(files)
          .appendTo($('#fileupload .files'));
        // Force reflow:
        fu._reflow = fu._transition && template.length &&
          template[0].offsetWidth;
        template.addClass('in');
        $('#loading').remove();
      });

  });
</script>

app/views/videos/delete_page.html.erb
<p>Delete <a href="<%=video_path(@video.id)%>"><%=@video.name%></a>?.<p>

<%= button_to "Delete", delete_video_with_key_path(@video.id, params[:delete_key]), method: :delete, class: "btn btn-danger", confirm: "Are you sure that you want to delete #{@video.name}?" %>

app/views/videos/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<div class="container">
<div class='row'>
  <div class = "col-xs-1"></div>
  <div class="upload-div col-xs-10">
    <div class"outside">
    <div class="fileupload center-block btn btn-primary">
    <%= s3_uploader_form callback_url: '/videos',
             id: "s3_uploader",
             callback_param: "document[file_url]",
             expiration: 2.hours.from_now.utc.iso8601,
             callback_method: "POST",
             max_file_size: 300.megabytes do %>
              <div class="choose-file-text">Choose File</div>
    <%= file_field_tag :file, multiple: false, class: "file-chooser-button" %>
  <% end %>
  </div>
  <div id="uploads_container"></div>
  </div>
  </div>
</div>
    <% @videos.each do |video| %>
    <div class="row">
      <div class="col-xs-2"></div>
      <div class="video-div col-xs-9">
        <%= link_to (video.name || "Untitled"), video_path(video.id) %>
      </div></div>
    <% end %>
</div>
<script id="template-upload" type="text/x-tmpl">
    <div class="progress progress-striped">
      <div class="bar progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
    </div>
</script>

app/views/videos/my_new.html.erb
<%= form_for Video.new, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="span7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span>Add files...</span>
                    <%= f.file_field :avatar %>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="icon-upload icon-white"></i>
                    <span>Start upload</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="icon-ban-circle icon-white"></i>
                    <span>Cancel upload</span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="icon-trash icon-white"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" class="toggle">
            </div>
            <div class="span5">
                <!-- The global progress bar -->
                <div class="progress progress-success progress-striped active fade">
                    <div class="bar" style="width:0%;"></div>
                </div>
            </div>
        </div>
        <!-- The loading indicator is shown during image processing -->
        <div class="fileupload-loading"></div>
        <br>
        <!-- The table listing the files available for upload/download -->
        <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
        </table>
    <% end %>
<script>
  var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td class="preview"><span class="fade"></span></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        {% if (file.error) { %}
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else if (o.files.valid && !i) { %}
            <td>
                <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
            </td>
            <td class="start">{% if (!o.options.autoUpload) { %}
                <button class="btn btn-primary">
                    <i class="icon-upload icon-white"></i>
                    <span>{%=locale.fileupload.start%}</span>
                </button>
            {% } %}</td>
        {% } else { %}
            <td colspan="2"></td>
        {% } %}
        <td class="cancel">{% if (!i) { %}
            <button class="btn btn-warning">
                <i class="icon-ban-circle icon-white"></i>
                <span>{%=locale.fileupload.cancel%}</span>
            </button>
        {% } %}</td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
            <td></td>
            <td class="name"><span>{%=file.name%}</span></td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
            <td class="preview">{% if (file.thumbnail_url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
            {% } %}</td>
            <td class="name">
                <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
            </td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td colspan="2"></td>
        {% } %}
        <td class="delete">
            <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                <i class="icon-trash icon-white"></i>
                <span>{%=locale.fileupload.destroy%}</span>
            </button>
            <input type="checkbox" name="delete" value="1">
        </td>
    </tr>
{% } %}
</script>



<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<%= javascript_include_tag 'jquery.ui.widget.js' %>
<!-- The Templates and Load Image plugins are included for the FileUpload user interface -->
<%= javascript_include_tag 'jquery.fileupload-process.js' %>
<%= javascript_include_tag 'tmpl.min.js' %>
<%= javascript_include_tag 'load-image.min.js' %>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<%= javascript_include_tag 'jquery.iframe-transport.js' %>
<%= javascript_include_tag 'jquery.fileupload.js' %>
<%= javascript_include_tag 'jquery.fileupload-ui.js' %>
<!-- add include_tag js files to config.assets.precompile in ...environments/production.rb if you have it in vendor/ assets -->

<script type="text/javascript" charset="utf-8">
    $(function () {
        // Initialize the jQuery File Upload widget:
        $('#fileupload').fileupload();
        // 
        // Load existing files:
        $.getJSON($('#fileupload').prop('action'), function (files) {
          var fu = $('#fileupload').data('blueimp-fileupload'), 
            template;
          fu._adjustMaxNumberOfFiles(-files.length);
          template = fu._renderDownload(files)
            .appendTo($('#fileupload .files'));
          // Force reflow:
          fu._reflow = fu._transition && template.length &&
            template[0].offsetWidth;
          template.addClass('in');
          $('#loading').remove();
        });

    });
</script>

app/views/videos/new.html.erb
<% if !@video.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
 
<div class="well">
  <%= form_for @video, html: { multipart: true } do |f| %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/videos/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-xs-12 col-md-offset-1"><div class="title-contatiner">
    <%if @owner_type == "owner" || @owner_type == "not signed in"%>
        <div class="title-div">
            <h1><%=@video.name || "Title"%> <button class="btn btn-default btn-sm edit-title-button"><%= fa_icon "pencil"%></button></h1>
        </div>
        <div class="edit-title-form buffer">
            <button class="btn btn-default btn-sm cancel-edit-button"><%= fa_icon "times"%></button>
            <%=form_for @video, role: "form",  class: "form" do |f|%>
    	   <%=f.text_field :name, class: "form-input inline"%>
    	   <%=f.submit "Set Title", class: "btn btn-default inline "%>
    	   <%end%>
        </div>

    <%elsif @owner_type == "not owner"%>
        <h1><%=@video.name%></h1>
    <%end%></div>
    <% if @video.processed == "processed" %>
    <video preload controls id="videoid" class="video-js vjs-default-skin" controls preload="auto" >
        <source src="<%=@video.url%>" type='video/mp4' />
    </video>
    <%elsif @video.processed == "processing"%>
        <div class="inline-block-sm border">
            Your video is currently being processed
        </div>
    <%else%>
        <div class="inline-block-sm border">
            Your video could not be processed
        </div>
    <%end%>
</div>
<div class="col-xs-10 col-md-3"><div class="links-area">
    <div class="inline-block-sm border">
        <p>Link to this page</p>
            <input type="text" class="link-text"readonly=true id="video-link" value="easyvid.heroku.com<%=video_path(@video.id) %>"/>
            <button class='my_clip_button' data-clipboard-text="<%="easyvid.heroku.com" + video_path(@video.id)%>" id='d_clip_button' title='Click me to copy to clipboard.'>
            <%= fa_icon "clipboard"%>
        </button>
    </div>
    <div class="inline-block-sm border">
        Views: <strong><%=@video.views%></strong>
    </div>
  <%if @owner_type == "owner"%>
  <div class="inline-block-sm border">
    <p><p>
    <%= button_to "Delete",  @video, method: :delete, class: "btn btn-danger delete-button", confirm: "Are you sure that you wish to delete #{@video.name}?" %>
</div>
  <%elsif @owner_type == "not signed in"%>
  <div class="inline-block-sm border">
    <p>Login to save this video on your account to allow future editing or deleting.</p>
    <p>Save this link if you might want to delete it.<br/>This link will not be shown again. 
        <input type="text" class="link-text" readonly=true id="video-link" value="easyvid.heroku.com<%=delete_video_page_path(@video.id, @video.delete_key)%>"/>
            <button class='my_clip_button2' data-clipboard-text="easyvid.heroku.com<%=delete_video_page_path(@video.id, @video.delete_key)%>" id='d_clip_button2' title='Click me to copy to clipboard.'>
        <%= fa_icon "clipboard"%>
    </button>
    </p>
</div>
<%end%>
  </div>
</div>
</div></div>
<script>
    $('document').ready(function(){
        var client = new ZeroClipboard( document.getElementById('d_clip_button') );
        var client2 = new ZeroClipboard( document.getElementById('d_clip_button2') );
        $('.edit-title-form').hide();
      $(".edit-title-button").click(function() {
        $('.edit-title-form').show();
        $(".title-div").hide();
    });
    $(".cancel-edit-button").click(function() {
        $('.edit-title-form').hide();
        $(".title-div").show();
    });
    $("#video-link").click(function(){
        this.select();
    });
    });
  </script>
  <script type="text/javascript">
  // Once the video is ready
  _V_("videoid").ready(function(){

    var myPlayer = this;    // Store the video object
    var aspectRatio = 9/16; // Make up an aspect ratio

    function resizeVideoJS(){
      // Get the parent element's actual width
      var width = document.getElementById(myPlayer.id()).parentElement.offsetWidth;
      width *= .9;
      // Set width to fill parent element, Set height
      myPlayer.width(width).height( width * aspectRatio );
    }

    resizeVideoJS(); // Initialize the function
    window.onresize = resizeVideoJS; // Call the function on resize
  });
</script>