config/routes.rb
VideoApp::Application.routes.draw do
  root to: 'videos#index'
  get "users/new", to: 'users#new', as: :signup
  post "/sessions", to: 'sessions#create', as: :sessions
  post '/users', to: 'users#create'
  delete '/sessions', to: 'sessions#destroy', as: :signout

  resources :videos, only: [:index, :create, :destroy, :show, :update]

  delete '/videos/:id/:delete_key', to: "videos#destroy", as: :delete_video_with_key

  get '/users/:id', to: 'users#show', as: :show_user

  get '/videos/:id/d/:delete_key', to: 'videos#delete_page', as: :delete_video_page

  get '/new', to: 'videos#new_new'

get '/hw/uploaded/:id', to: 'site#index'
  get '/hw/encoded/:id', to: 'site#index'

  post '/hw/uploaded/:id', to: 'my_heywatch#upload_complete'
  post '/hw/encoded/:id', to: 'my_heywatch#encode_complete'

end

app/views/layouts/_header.html.erb
<div class="navbar-inverse navbar-fixed-top custom-nav">
      <div class="navbar-header pull-left">
        <a class="navbar-brand hidden-xs" href="/">Video</a>
      </div>
      <div class="navbar-header pull-right rightside in-em">
            <% if signed_in? %>
            <p class="navbar-text navbar-right signed-in">Welcome, <%=current_user.name%>
              <%=image_tag("http://www.gravatar.com/avatar.php?gravatar_id=#{Digest::MD5::hexdigest(current_user.email)}", :alt => 'Avatar', :class => 'avatar',  wdith: "40px", height: "40px", class:"avatar")%>
                <%= link_to "Sign out", signout_path, method: "delete", class: 'sign-link' %>
              </p>
            <% else %>
            <div class="nav navbar-nav">
              <div class="in-im">
              <%= link_to "Sign up", signup_path, class: 'sign-link'%>
            </div><div class="in-im">
              <%= form_for(:session, url: sessions_path, class: 'navbar-form', role: 'login') do |f| %>
                  <%= f.text_field :email, placeholder: "Email" %>
                  <%= f.password_field :password, placeholder: "Password", class: "password-field"%>
                  <button type="submit"><%= fa_icon "sign-in" %></input>
                <% end %></div>
              </div>
            <% end %>
        </div>
</div>
<% if flash[:error]  %>
        <div class="alert alert-danger">
          <%=flash[:error]%>
        
        </div>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="//vjs.zencdn.net/4.2/video-js.css" rel="stylesheet">
<script src="//vjs.zencdn.net/4.2/video.js"></script>
  <title>EasyVid</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>